services:
  - type: web
    name: hospital-portal-demo
    runtime: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python create_superuser.py"
    startCommand: "python manage.py migrate && python create_superuser.py && gunicorn employee_management.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2  # IMPORTANT: Caps Gunicorn workers at 2 to stay under 512MB RAM!
      - key: DJANGO_SECRET_KEY
        value: "replace-me-with-a-secure-key"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "replace-me-with-username"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "replace-me-with-email@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "replace-me-with-password"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
    autoDeploy: true
